### ISSUE TITLE
Websocket live event properties behaviour changed unexpectedly

### ISSUE THREAD

**Issue by ilovecherries** [randomouscrap98/contentapi#106]
It seems recently or after I changed my client to support websocket requests, it looks like the events that I get from the API use numbers now to specify event types.
![Screenshot_20220407_093201](https://user-images.githubusercontent.com/18371895/162210711-8f620ebc-f61a-4cdc-ab91-3a2eb896a918.png)

In the meantime, anyone else who is making a client that specifically uses the events until this bug is fixed, it looks like this is where the values are for events:
- https://github.com/randomouscrap98/contentapi/blob/a5f36c37277cf329a1ab3dc19ce60ac412329c27/contentapi.db/Enums.cs#L19-L25
- https://github.com/randomouscrap98/contentapi/blob/a5f36c37277cf329a1ab3dc19ce60ac412329c27/contentapi/Live/EventType.cs#L3-L12

**Comment by 12Me21** [comment]
adding secret features while ur asleep,,
