### ISSUE TITLE
downscaling jpeg images

### ISSUE THREAD

**Issue by 12Me21** [randomouscrap98/contentapi#133]
small downscaled jpeg files look really bad, because the format/quality is preserved.
below a certain size, you should probably increase the jpeg quality setting, or convert to png.
(for things like avatars, thumbnails, icons, etc.)

maybe have a `?png=true` query param for `/File/raw`?

**Comment by 12Me21** [comment]
oh, and be careful of requests like `api/File/raw/very-large-jpeg?png=true`
i.e. the image would look identical, but with a massively increased filesize
maybe set a size limit of ~300px or something?

**Comment by randomouscrap98** [comment]
I'm pretty sure that filtering is also to blame, to downscaling algorithm is probably trash. But yeah the jpeg is probably a big part of it too. Hm... I can look into it. What sizes are we talking here, 50?

**Comment by randomouscrap98** [comment]
completed with https://github.com/randomouscrap98/contentapi/commit/0fef94e00bdfc3e4ff81b54132fb02e2996127b3
