### ISSUE TITLE
Userlist for chat

### ISSUE THREAD

**Issue by randomouscrap98** [randomouscrap98/contentapi#81]
There's a lot to unpack here. I have a design for handling all the ridiculous complication of per-room user statuses, however, I'm starting to get the feeling that it's not actually that important to have, and it would ridiculously simplify everything if we just had a single, global userlist, just like in old chat. So, until that decision is made, I'm probably not going to add the design for the complicated one here. The simple one would be... well, a simple auto-tracker. It would just say if you're active or inactive, just like the old chat, and active means we're receiving something from you in the last idk seconds. It could be a ping like before, OR the users could have limited control over it, but only for a "singular" list. This would also simplify hiding quite a lot.

**Comment by BrokenR3C0RD** [comment]
Maybe a mix of the two? Track global site status, you can see if someone's currently online on the site (but it could be disabled of course) and maybe a small status message, and then on specific chats, you can use the autotracker you mentioned (so people could hide their status on a specific page). If global status is hidden, then you're completely hidden

**Comment by randomouscrap98** [comment]
A mix of the two is part of the "per-room" status system though. I asked everyone and got a resounding "we definitely want the per-room userlist", so I'm going with the complex option.

I was going to write down the design but I ended up already implementing most of the core. Still need to unit test, gosh I'm so tired of writing tests lol 0db20320d2d2333c1f7341a7d57fae6467d3718b

**Comment by randomouscrap98** [comment]
Done in... I don't remember, something a while ago
