### ISSUE TITLE
updating user data fails

### ISSUE THREAD

**Issue by y-ack** [randomouscrap98/contentapi#94]
api/run/index.html?t=user

try to update user data, e.g. avatar hash:
`Error 400: {"errors":{"user":["The user field is required."],"super":["Error converting value {null} to type 'System.Boolean'. Path 'super', line 1, position 82."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-b458d64fcf61a2ea49030b5c9ad7aa7c-17038bacf160b47a-00"}`

encountered by Mochameinko during avatar update

Perska: "if you omit the super field* it should work?
as in erase it"
(*supers omitting the field will unset their super status.)

**Comment by randomouscrap98** [comment]
I believe this was fixed in 489bbddfd3a7eb68e0067248350bf96064fe8dc6
