### ISSUE TITLE
Settable hash on file upload

### ISSUE THREAD

**Issue by randomouscrap98** [randomouscrap98/contentapi#95]
Allow the user to state their desired hash (just like with content) on file upload. Remember that the hash has strict limits, such as 8 character minimum and only a-z and -

**Comment by y-ack** [comment]
nnn hmm.. are we sure about this... it still feels like something a good frontend could translate, and users might have different names for things

**Comment by randomouscrap98** [comment]
What do you mean? Hash setting is already a feature on the backend, for all content except files. Files are also content, and so automatically support it, it's just a matter of adding a field to the file upload, because files require an additional form. We can STILL do some kind of translation if that's what you want, but custom hashes are just a thing...

Also, the custom hashes don't collide with automatic hashes. Automatic hashes are 5 characters like before, and custom hashes must be at least 8 characters (I checked).

What is the concern with the custom hashing? It's no additional effort, and we don't HAVE to use it, and this is a tiny community anyway, I don't think we're going to have problems...

**Comment by y-ack** [comment]
oh, hmm. ok.
